# Mandatory settings

blog_theme: light # Or use dark
name: Rahul Jain
paginate: 5
url: http://rahulja.in
description: Articles and Profile of Rahul Jain. He is a Full-Stack Engineer and web enthusiast living in Hyderabad, India.
timezone: Asia/Kolkata
encoding: utf-8

# Optional settings
baseurl: # Set if blog doesn't sit at the root of the domain (format: /blog)
about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
discus_identifier: rahulja-in # Add your Disqus identifier
ga_analytics: UA-75936371-1 # Add your GA Tracking Id
local_fonts: true # Change to true if you wish to use local fonts
rss_enabled: true # Change to false if not
social_links:
  facebook: xRahulJain # Add your Facebook handle
  github: xRahul # Add your GitHub handle
  linkedin: xRahulJain # Add your LinkedIn handle
  twitter: xRahulJain # Add your Twitter handle
  email: rahul_jain@live.in # Add your Email address
  stackoverflow: 1435626/rahul # Add your stackoverflow id/name
  freecodecamp: xrahul # Add your freecodecamp username
  #bitcoin: 1BmYjgdCkY6P8tmmxjm4f5stDK7vJ6VcQN # Add your Bitcoin wallet ID
  flattr: "https://flattr.com/submit/auto?fid=djeqkn&url=http%3A%2F%2Frahulja.in"


# Process and render draft posts
# show_drafts: false
# Publish posts or collection documents with a future date
# future: false
# Render posts that were marked as unpublished
# unpublished: false
# Produce an index for related posts.
# lsi: true

author:
  name: Rahul Jain
  email: rahul_jain@live.in
  uri: http://rahulja.in/about

# Important settings (change at own risk)

paginate_path: /posts/page/:num/
permalink: posts/:slug

# Important settings
assets:
  digest: false
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {jpegoptim: all}}
  source_maps: false
  sources:
    - _assets/yarn
    - _assets/javascripts
    - _assets/stylesheets
  baseurl: http://rahulja.in

collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
  my_projects:
    output: true
    permalink: /project/:slug/

# using defaults- https://jekyllrb.com/docs/configuration/
defaults:
  -
    scope:
      path: ""
      type: my_projects
    values:
      layout: articles_by_project
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default

exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - README.md
  - .jekyll-metadata
  - package.json
  - vendor/

plugins:
  - jemoji
  - jekyll-assets
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-last-modified-at

#Custom variables
attribution:
  template:
    project_url: https://github.com/nielsenramon/chalk
    creator_url: http://nielsenramon.com

