# Site settings
title: Rahul Jain
email: rahul_jain@live.in
url: http://rahulja.in
description: "Portfolio of a Software Engineer."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 8f908a #80B3FF
  secondary: 3d3d3a #FD6E8A
  secondary-dark: 272822 #A2122F

# Footer settings
footer:
  copyright: Rahul Jain
  location: Location
  social: Around the Web
  email_header: Email
  footer404: fix-to-bottom

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/rahulgr8888
  - title: facebook
    url: http://www.facebook.com/rahulgr8888
  - title: google-plus
    url: https://plus.google.com/+RahulJain17
  - title: linkedin
    url: http://in.linkedin.com/in/rahulgr8888/en
  - title: github
    url: http://github.com/rahulgr8888

# Postal address (add as many lines as necessary)
address:
  - line: Plot - 112, Sector 44
  - line: Gurgaon, 122 001, India

# Credits content
email: '<h4><a id="footer_emailID" href="mailto:rahul_jain@live.in">rahul_jain@live.in</a></h4>'

# Build settings
markdown: kramdown
permalink: pretty

#404 settinge
404titleappend: 404

#Github settings
gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-mentions