#Mandatory
name: Rahul Jain
url: http://rahulja.in
description: Articles and Profile of Rahul Jain. He is a Full-Stack Engineer and web enthusiast living in Gurgaon, India.

blog_theme: light # Or use dark
timezone: Asia/Kolkata
encoding: utf-8

# Process and render draft posts
# show_drafts: false
# Publish posts or collection documents with a future date
# future: false
# Render posts that were marked as unpublished
# unpublished: false
# Produce an index for related posts.
# lsi: true

author:
  name: Rahul Jain
  email: rahul_jain@live.in
  uri: http://rahulja.in/about

paginate: 5
paginate_path: "/posts/page/:num/"
permalink: posts/:slug

# Optional Settings
discus_identifier: rahulja-in # Add your Disqus identifier
ga_analytics: UA-75936371-1 # Add your GA Tracking Id
rss_enabled: true # Change to false if not
about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
social_links:
  facebook: xRahulJain # Add your Facebook handle
  github: xRahul # Add your GitHub handle
  linkedin: xRahulJain # Add your LinkedIn handle
  twitter: xRahulJain # Add your Twitter handle
  email: rahul_jain@live.in # Add your Email address
  stackoverflow: 1435626/rahul # Add your stackoverflow id/name
  freecodecamp: xrahul # Add your freecodecamp username
  bitcoin: 1BmYjgdCkY6P8tmmxjm4f5stDK7vJ6VcQN # Add your Bitcoin wallet ID

# Important settings
assets:
  digest: false
  compress:
    css: false
    js: false
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/images
    - _assets/images/favicons
    - _assets/javascripts
    - _assets/stylesheets
  baseurl: http://rahulja.in

collections:
  my_tags:
    output: true
    permalink: /tag/:slug/

# using defaults- https://jekyllrb.com/docs/configuration/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - README.md
  - feed.xml_asdf
  - vendor/
  - .jekyll-metadata

gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-seo-tag

#Cusstom variables
attribution:
  template:
    project_url: https://github.com/nielsenramon/chalk
    creator_url: http://nielsenramon.com

