# Mandatory settings
name: Rahul Jain
paginate: 5
paginate_path: "/posts/page/:num/"
url: http://rahulja.in
blog_theme: light # Or use dark

# Optional Settings
discus_identifier: rahulja-in # Add your Disqus identifier
ga_analytics: UA-75936371-1 # Add your GA Tracking Id
rss_enabled: true # Change to false if not
about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
social:
  facebook: xRahulJain # Add your Facebook handle
  github: xRahul # Add your GitHub handle
  linkedin: xRahulJain # Add your LinkedIn handle
  twitter: xRahulJain # Add your Twitter handle
  email: rahul_jain@live.in # Add your Email address
  stackoverflow: 1435626/rahul # Add your stackoverflow id/name
  freecodecamp: xrahul # Add your freecodecamp username
  bitcoin: 1BmYjgdCkY6P8tmmxjm4f5stDK7vJ6VcQN # Add your Bitcoin wallet ID

# Important settings
assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/images/favicons
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
permalink: posts/:slug

#Cusstom variables
attribution:
  template:
    project_url: https://github.com/nielsenramon/chalk
    creator_url: http://nielsenramon.com