# Site settings
title: Rahul Jain
email: rahul_jain@live.in
url: http://rahulja.in
description: "Portfolio of a Software Engineer."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Rahul Jain
  location: Location
  social: Around the Web
  credits: Work

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/rahulgr8888
  - title: facebook
    url: http://www.facebook.com/rahulgr8888
  - title: google-plus
    url: https://plus.google.com/+RahulJain17
  - title: linkedin
    url: http://in.linkedin.com/in/rahulgr8888/en
  - title: github
    url: http://github.com/rahulgr8888

# Postal address (add as many lines as necessary)
address:
  - line: Plot - 112, Sector 44
  - line: Gurgaon, 122 001, Haryana, India

# Credits content
credits: 'Software Engineer <a href="http://www.shopclues.com">@Shopclues</a>'

# Build settings
markdown: kramdown
permalink: pretty